### ISSUE TITLE
Add diagnostic messages for violated mock expectations

### ISSUE THREAD

**Issue by tudortimi-ifx** [nosnhojn/svmock#5]
(I guess this is already on the list.)

Need detailed messages of what went wrong (not called enough times, wrong arguments, etc.).

**Comment by nosnhojn** [comment]
committed to master. not super ideal considering the limit of what the code understands due to the side effects of my intended ignorance of data types and aggregate/scalar types, but after some serious haggling I think it's useful. scaler numeric/string types are printed clearly. aggregate numeric/string types are limited to the beginning/end elements (15 characters of each). complex types are printed as <unknown> b/c there's not much more I can do with them.
